#ifndef APP_PINS_INC
#define APP_PINS_INC

// ONBOARD
#define BUILTIN_LED UC_PIN_13

// BUTTONS
#define BUTTON_MODE_PIN UC_PIN_2
#define BUTTON_SET_PIN UC_PIN_3

// PUMP
#define PUMP0_PIN UC_PIN_10
#define PUMP1_PIN UC_PIN_9

// LEVEL
#define LEVEL_VCC_PIN UC_PIN_A3
#define LEVEL_ADC_PIN UC_PIN_A1
#define LEVEL_BUZZER_PIN UC_PIN_A2

// LCD
#define LCD_VSS GROUND
#define LCD_VCC VCC
#define LCD_V0 GROUND
#define LCD_RS_PIN UC_PIN_12
#define LCD_RW GROUND
#define LCD_ENABLE_PIN UC_PIN_11
#define LCD_D0_PIN GROUND
#define LCD_D1_PIN GROUND
#define LCD_D2_PIN GROUND
#define LCD_D3_PIN GROUND
#define LCD_D4_PIN UC_PIN_4
#define LCD_D5_PIN UC_PIN_5
#define LCD_D6_PIN UC_PIN_6
#define LCD_D7_PIN UC_PIN_7
#define LCD_A UC_PIN_A0 // via RES of 1K
#define LCD_K GROUND

#endif // APP_PINS_INC
