#define BUTTON0 UC_PIN_2
#define BUTTON1 UC_PIN_3
#define BUILTIN_LED UC_PIN_13
#define SERVO UC_PIN_A2

#define LCD_RS_PIN UC_PIN_12
#define LCD_ENABLE_PIN UC_PIN_11
#define LCD_D4_PIN UC_PIN_7
#define LCD_D5_PIN UC_PIN_6
#define LCD_D6_PIN UC_PIN_5
#define LCD_D7_PIN UC_PIN_4
#define LCD_RW GROUND
#define LCD_VSS GROUND
#define LCD_VCC VCC
#define LCD_V0 GROUND
